### PR TITLE
Print correct currmovenumber starting with 1

### PR DESCRIPTION
**Pull request by joergoster**
by moving the output after the increment of the madeMoves variable.
No functional change.

### CODE REVIEW

**Comment by joergoster** [comment]
Sample output after go depth 17 on the start position:
```
info depth 16 seldepth 22 score cp 11 nodes 40595656 nps 2786000 time 14566 pv d2d4 d7d5 e2e3 b8c6 c2c4 d5c4 f1c4 e7e5 g1e2 g8f6 b1c3 f8d6 e1g1 e8g8 c3b5 c8f5 
info depth 17 currmove d2d4 currmovenumber 1
info depth 17 currmove b2b4 currmovenumber 2
info depth 17 currmove c2c3 currmovenumber 3
info depth 17 currmove c2c4 currmovenumber 4
info depth 17 currmove d2d3 currmovenumber 5
info depth 17 currmove a2a3 currmovenumber 6
info depth 17 currmove e2e3 currmovenumber 7
info depth 17 currmove e2e4 currmovenumber 8
info depth 17 currmove f2f4 currmovenumber 9
info depth 17 currmove g2g3 currmovenumber 10
info depth 17 currmove h2h3 currmovenumber 11
info depth 17 currmove b1c3 currmovenumber 12
info depth 17 currmove g1f3 currmovenumber 13
info depth 17 currmove a2a4 currmovenumber 14
info depth 17 currmove f2f3 currmovenumber 15
info depth 17 currmove b1a3 currmovenumber 16
info depth 17 currmove g2g4 currmovenumber 17
info depth 17 currmove b2b3 currmovenumber 18
info depth 17 currmove h2h4 currmovenumber 19
info depth 17 currmove g1h3 currmovenumber 20
info depth 17 seldepth 23 score cp 11 nodes 61057640 nps 2844000 time 21466 pv d2d4 d7d5 e2e3 b8c6 c2c4 d5c4 f1c4 e7e5 g1e2 g8f6 b1c3 f8d6 e1g1 e8g8 c3b5 c8f5 b5d6 
bestmove d2d4
```

**Comment by Disservin** [comment]
Hi joergoster,

thanks for the pr it indeed makes more sense that way !

**Comment by joergoster** [comment]
Hi, just something I noticed after a quick try of your engine.

**Comment by Disservin** [comment]
thanks for brining my attention to this, the culprit seems to be `use less time on obvious moves` `500cadf`. Which is very weird since it A. doesnt (shouldn't) affect the bench. 2. Bench calls aspiration window directly so not iterative deepening isnt even used.

**Comment by joergoster** [comment]
Sure. Looks good now.
`2582981 nodes 2263000 nps`

**Pull request merged**
