### PR TITLE
NNUE

### PR DESCRIPTION
**Pull request by Disservin**
This PR changes the evaluation used in smallbrain from psqt + material, to NNUE.
For now the architecture is quite simple:

There are 768 inputs to cover all combinations where a piece might be.
The hidden layer consists of 256 neurons. 
This gives us one output neuron that gives us the centipawn score.

The accumulator is efficiently updated in makemove/unmakemove, which leads to a big performance increase and thus elo gain.

The net was trained on data given by Luecx (from [Koivisto](https://github.com/Luecx/Koivisto)), as well as using his [CUDAD trainer](https://github.com/Luecx/CudAD). 
He has played a major role in explaining to me how to train and use a NNUE for chess engines and I am thankful for all the support he has provided.
The network architecture will hopefully be expanded in the future, together with me generating my own training data.
Overall this pull request is absolutely massive: 640 additions and 312 deletions.

There are some uci info fixes as well as code cleanups and well the removal of HCE.

Results against master:

    ELO   | 504.32 +- 46.09 (95%)
    CONF  | 8.0+0.08s Threads=1 Hash=8MB
    GAMES | N: 1000 W: 920 L: 24 D: 56
    
    ELO   | 586.77 +- 59.68 (95%)
    CONF  | 40.0+0.40s Threads=1 Hash=64MB
    GAMES | N: 1000 W: 949 L: 15 D: 36

### CODE REVIEW

**Comment by joergoster** [comment]
Wow, that's quite a massive gain! Congrats!

As far as I can tell you aren't using SIMD instructions by now. Is this correct?
Maybe this will help me to finally get a grasp on understanding this NNUE stuff ...

**Comment by Disservin** [comment]
Ah that’s very cool! I’m also quite interested in the results. You have to divide the output by some scalar number to make sure you don’t overflow, at least that’s how luecx explained it to me. So S1 is 64 and 256 is S2. You could also use 128 instead of 64 and it shouldn’t have a big impact. What is the name of your branch ?

**Comment by joergoster** [comment]
I see. Thanks again.
It's not online right now. Unfortunately, there seems to be a bug somewhere.
It doesn't work under cutechess-cli, always terminating. Will have to look at it.

Here is a 10 second search with 1 thread on the start position which looks ok to me, though.

> info depth 26 seldepth 44 multipv 1 score cp 27 nodes 10329278 nps 1032721 hashfull 1000 tbhits 0 time 10002 pv e2e4 c7c5 g1f3 e7e6 c2c3 d7d5 e4d5 e6d5 f1b5 b8c6 d2d4 f8d6 d4c5 d6c5 e1g1 a7a6 b5c6 b7c6 b1d2 g8e7 d2b3 c5b6 f1e1 e8g8 c1e3 b6e3 e1e3 d8c7 e3e1 f8e8 a1c1 c6c5
> bestmove e2e4 ponder c7c5

**Comment by Disservin** [comment]
> I see. Thanks again. It's not online right now. Unfortunately, there seems to be a bug somewhere. It doesn't work under cutechess-cli, always terminating. Will have to look at it.
> 
> Here is a 10 second search with 1 thread on the start position which looks ok to me, though.
> 
> > info depth 26 seldepth 44 multipv 1 score cp 27 nodes 10329278 nps 1032721 hashfull 1000 tbhits 0 time 10002 pv e2e4 c7c5 g1f3 e7e6 c2c3 d7d5 e4d5 e6d5 f1b5 b8c6 d2d4 f8d6 d4c5 d6c5 e1g1 a7a6 b5c6 b7c6 b1d2 g8e7 d2b3 c5b6 f1e1 e8g8 c1e3 b6e3 e1e3 d8c7 e3e1 f8e8 a1c1 c6c5
> > bestmove e2e4 ponder c7c5

Once you get it working properly you might want to give [matetrack ](https://github.com/vondele/matetrack) a try. Would be interesting to see how a smaller net compares to this big one.

**Comment by Disservin** [comment]
Ah cool, can I find this anywhere on your profile?

**Comment by joergoster** [comment]
Ich habe den neuen Branch [nnue-small](https://github.com/joergoster/Stockfish/tree/nnue-small) gerade hochgeladen, und noch ein weiteres Testresultat dazu.
Dein kleines Netz bringt also ca. 15 bis 20 Elo in Stockfish, immer vorausgesetzt mit dem Code ist alles in Ordnung. :-)

**Comment by joergoster** [comment]
Hier https://github.com/joergoster/Stockfish/commit/140a3c9fd46f10d6e7645c26a4938427573b549c ist die neue und korrigierte Version. Der Elozuwachs für diese Version liegt bei ungefähr 40. Wahrlich nicht schlecht für so ein kleines Netz!

**Pull request merged**
